#!/bin/bash

DIR=`dirname $0`
. $DIR/functions

EVENTDIR=$TRACING_DIR/events

function cnt_trace() {
	    grep -v '^#' $TRACING_DIR/trace | head -10000 | wc -l
}

#set -x

echo '** DISABLE TRACING'
echo 0 > $TRACING_DIR/tracing_on || exit -1
echo > $TRACING_DIR/trace || exit -1

cnt=`cnt_trace`
if [ $cnt -ne 0 ]; then
   exit -1
fi


echo '** ENABLE EVENTS'

echo 1 > $EVENTDIR/enable || exit -1

echo '** ENABLE TRACING'
echo 1 > $TRACING_DIR/tracing_on || exit -1

cnt=`cnt_trace`
if [ $cnt -eq 0 ]; then
   exit -1
fi

# powerpc uses .schedule
func="schedule"
x=`trace-cmd list -f '^\.schedule$' | wc -l`
if [ "$x" -eq 1 ]; then
   func=".schedule"
fi

echo '** SET TRACEOFF'

echo "$func:traceoff" > $TRACING_DIR/set_ftrace_filter

cnt=`grep schedule $TRACING_DIR/set_ftrace_filter | wc -l`
if [ $cnt -ne 1 ]; then
   exit -1
fi

cnt=`cnt_trace`
sleep 1
cnt2=`cnt_trace`

if [ $cnt -ne $cnt2 ]; then
   exit -1;
fi

on=`cat $TRACING_DIR/tracing_on`
if [ $on != "0" ]; then
	exit -1
fi

line1=`cat $TRACING_DIR/trace | tail -1`
sleep 1
line2=`cat $TRACING_DIR/trace | tail -1`

if [ "$line1" != "$line2" ]; then
   exit -1
fi

echo > $TRACING_DIR/trace || exit -1

cnt=`cnt_trace`
if [ $cnt -ne 0 ]; then
   exit -1
fi

echo "!$func:traceoff" >> $TRACING_DIR/set_ftrace_filter

cnt=`grep schedule $TRACING_DIR/set_ftrace_filter | wc -l`
if [ $cnt -ne 0 ]; then
   exit -1
fi

on=`cat $TRACING_DIR/tracing_on`
if [ $on != "0" ]; then
	exit -1
fi

echo "$func:traceon" > $TRACING_DIR/set_ftrace_filter

cnt=`grep schedule $TRACING_DIR/set_ftrace_filter | wc -l`
if [ $cnt -ne 1 ]; then
   exit -1
fi

cnt=`cnt_trace`
if [ $cnt -eq 0 ]; then
   exit -1
fi

on=`cat $TRACING_DIR/tracing_on`
if [ $on != "1" ]; then
	exit -1
fi


echo "!$func:traceon" >> $TRACING_DIR/set_ftrace_filter

cnt=`grep schedule $TRACING_DIR/set_ftrace_filter | wc -l`
if [ $cnt -ne 0 ]; then
   exit -1
fi

check_sleep() {
    val=$1
    sleep 1
    cat $TRACING_DIR/set_ftrace_filter
    on=`cat $TRACING_DIR/tracing_on`
    if [ $on != "$val" ]; then
	exit -1
    fi
}


echo "$func:traceoff:3" > $TRACING_DIR/set_ftrace_filter
check_sleep "0"
echo 1 > $TRACING_DIR/tracing_on
check_sleep "0"
echo 1 > $TRACING_DIR/tracing_on
check_sleep "0"
echo 1 > $TRACING_DIR/tracing_on
check_sleep "1"
echo "!$func:traceoff:0" > $TRACING_DIR/set_ftrace_filter

if grep -e traceon -e traceoff $TRACING_DIR/set_ftrace_filter; then
    exit -1
fi

echo 0 > $EVENTDIR/enable

exit 0
