#!/bin/bash

DIR=`dirname $0`
. $DIR/functions

version=`uname -r`
modules=`find /lib/modules/$version -name '*.ko' | sed -e 's,^.*/\([^/]*\)\.ko,\1,' -e 's/-/_/g'`
loaded=`lsmod | cut -d' ' -f1`
for mod in $modules; do
	# skip ring buffer benchmark as that can cause problems with the test
	if [ $mod == "ring_buffer_benchmark" ]; then
		continue;
	fi
	if ! echo $loaded | grep -q $mod; then
		if ! modprobe $mod ; then
			continue;
		fi
		# make sure there's functions to trace.
		func=`grep "\\[$mod\\]" $TRACING_DIR/available_filter_functions | head -1 | cut -d' ' -f1`
		rmmod $mod
		if [ -z "$func" ]; then
			continue
		fi
		break
	fi
done
echo "Using module: $mod  Function: $func"
module=$mod
# module=uinput
#func=uinput_release
modprobe $module
rmmod $module

set_ftrace_filter=$TRACING_DIR/set_ftrace_filter
set_ftrace_notrace=$TRACING_DIR/set_ftrace_notrace

> $set_ftrace_filter
> $set_ftrace_notrace

echo function > $TRACING_DIR/current_tracer || exit 1

echo "Testing function enabled"
found=0
locs=''
modprobe $module
while :; do
    loc=`grep "^$module " /proc/modules | cut -d' ' -f6`
    if echo $locs | grep -q $loc ; then
	echo nop > $TRACING_DIR/current_tracer || exit 1
	> $set_ftrace_filter || exit 1
	break
    fi
    locs="$locs $loc"
    echo $func >> $set_ftrace_filter || exit 1
    rmmod $module
    modprobe $module
done
rmmod $module
echo "  Success"

locs=''
echo "Testing function disabled"
modprobe $module
while :; do
    loc=`grep "^$module " /proc/modules | cut -d' ' -f6`
    if echo $locs | grep -q $loc ; then
	echo nop  > $TRACING_DIR/current_tracer || exit 1
	> $set_ftrace_filter || exit 1
	break
    fi
    locs="$locs $loc"
    echo nop  > $TRACING_DIR/current_tracer || exit 1
    echo $func >> $set_ftrace_filter || exit 1
    rmmod $module
    echo function > $TRACING_DIR/current_tracer
    modprobe $module
done
rmmod $module
echo "  Success"
echo nop  > $TRACING_DIR/current_tracer || exit 1

locs=''
echo "Testing notrace set"
modprobe $module
while :; do
    loc=`grep "^$module " /proc/modules | cut -d' ' -f6`
    if echo $locs | grep -q $loc ; then
#echo "  done"
#	exit 0
	echo nop  > $TRACING_DIR/current_tracer || exit 1
	> $set_ftrace_filter || exit 1
	break
    fi
    locs="$locs $loc"
    echo nop  > $TRACING_DIR/current_tracer || exit 1
    echo $func >> $set_ftrace_notrace || exit 1
    rmmod $module
    echo function > $TRACING_DIR/current_tracer
    modprobe $module
done
rmmod $module
echo "  Success"
echo nop  > $TRACING_DIR/current_tracer || exit 1
exit 0
