#!/bin/bash

DIR=`dirname $0`
. $DIR/functions

x=`trace-cmd record -p function -l '*account_user_time' --func-stack cat $TRACING_DIR/options/func_stack_trace  | head -1`
# disable function stack trace option (trace-cmd should have done it itself)
trace-cmd start -p function -l '*account_user_time'
trace-cmd start -p nop
echo > $TRACING_DIR/set_ftrace_filter
if [ "$x" -eq 1 ]; then
	exit 0
fi
exit 1
