#!/bin/bash

DIR=`dirname $0`
. $DIR/functions

#set -x

trace-cmd start -b 1407 -p function || exit 1
let x=0
while [ $x -lt 1000 ]; do
	c=`grep '^overrun' $TRACING_DIR/per_cpu/cpu0/stats | cut -d' ' -f2`
	if [ $c -gt 0 ]; then
		break
	fi
	let x=$x+1
done
if [ $x -eq 1000 ]; then
	echo "FAILED: Overrun never hit"
	exit 1
fi

trace-cmd stop

c=`grep '^entries' $TRACING_DIR/per_cpu/cpu0/stats | cut -d' ' -f2`
if [ $c -eq 0 ]; then
	echo "FAILED: No entries found"
	exit 1
fi

echo set buffer to 1000kb

echo 1000 > $TRACING_DIR/buffer_size_kb || exit 1

echo spawn cat trace_pipe
cat $TRACING_DIR/trace_pipe > /dev/null &

echo read trace
let x=0
while [ $x -lt 60 ]; do
	c=`grep -v '#' $TRACING_DIR/trace |wc -l`
	if [ $c -eq 0 ]; then
		break
	fi
	let x=$x+1
done

echo disable tracing

echo 0 > $TRACING_DIR/tracing_on

echo wait for trace to become empty

c=1
last_c=2

while [ $c -gt 0 ]; do
	sleep 1
	c=`grep -v '#' $TRACING_DIR/trace | wc -l`
	if [ $c -eq $last_c ]; then
		echo "trace_pipe stopped updating c=$c last_c=$last_c"
		exit
	fi
	last_c=$c
done
echo kill trace_pipe
kill %1

echo check count
if [ $x -eq 1000 ]; then
	echo "FAILED: pipe never emptied"
	exit 1
fi

c=`grep '^entries' $TRACING_DIR/per_cpu/cpu0/stats | cut -d' ' -f2`
if [ $c -ne 0 ]; then
	echo "FAILED: entries should be zero"
	exit 1
fi

echo 1 > $TRACING_DIR/tracing_on
echo 0
