#!/bin/bash

DIR=`dirname $0`
. $DIR/functions

arg="sleep 10"
if [ $# -gt 0 ]; then
	arg="$@"
fi

tmpfile=/tmp/tmpfile.$$

for tracer in `cat $TRACING_DIR/available_tracers`; do
	if [ $tracer == "nop" ]; then
		continue;
	fi
	echo "Testing tracer $tracer"
	echo $tracer > $TRACING_DIR/current_tracer
	echo "running $arg"
	$arg
	echo 0 > $TRACING_DIR/tracing_on
	cat $TRACING_DIR/trace > $tmpfile
	echo nop > $TRACING_DIR/current_tracer
	cnt=`wc -l $tmpfile | cut -d ' ' -f1`
	if [ $cnt -gt 300 ]; then
		head -100 $tmpfile
		echo '[...]'
		tail -100 $tmpfile
	else
		cat $tmpfile
	fi
	echo 1 > $TRACING_DIR/tracing_on
done
