#!/bin/bash

DIR=`dirname $0`
$DIR/functions

TRACECMD=trace-cmd

TIME=2

trace-cmd record --nosplice -e sched sleep 1 >/dev/null 2>&1
nosplice=$?
if [ $nosplice -ne 0 ]; then
    echo " --nosplice not supported"
fi

# test plugins

run_plugin_test() {
    plugin=$1
    extra=$2

    echo "Running $plugin $extra"
    if ! $TRACECMD record -p $plugin $extra sleep $TIME; then
	echo "FAILED record -p $plugin $extra"
	exit -1
    fi
    if ! $TRACECMD report > /tmp/test-trace.out ; then
	echo "FAILED report for $plugin $extra"
	exit -1
    fi
    head -500 /tmp/test-trace.out
}

plugins=`cat $TRACING_DIR/available_tracers`;
for p in $plugins; do
    run_plugin_test $p || exit 1
    if [ $nosplice -eq 0 ]; then
	run_plugin_test $p --nosplice || exit 1
    fi
done

echo success
exit 0
